export const LOAD_USERS = 'LOAD_USERS';
export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS';
export const LOAD_USERS_FAILURE = 'LOAD_USERS_FAILURE';
export const ADD_USER = 'ADD_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const DELETE_USER = 'DELETE_USER';

export const LOAD_USER_BY_EMAIL = 'LOAD_USER_BY_EMAIL';
export const LOAD_USER_BY_EMAIL_SUCCESS = 'LOAD_USER_BY_EMAIL_SUCCESS';
export const LOAD_USER_BY_EMAIL_FAILURE = 'LOAD_USER_BY_EMAIL_FAIL';
